- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - ruby-build
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - readline
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - ansible
      - git
      - git-flow
      - heroku-toolbelt
      - tmux
      - peco
      - nvm
      - rbenv
#      - rbenv-gem-rehash
      - ruby-build
      - the_silver_searcher
#      - vim
#      - macvim
#      - { name: macvim, install_options: [with-cscope, with-lua, override-system-vim] }
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - node
      - svn
      - { name: svn, install_options: [unicode-path] }

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - firefox-ja
      - flash
      - google-chrome
      - google-japanese-ime
      - iterm2
      - java
      - sourcetree
#      - java6
#      - karabiner
#      - phpstorm
#      - rubymine
      - slack
      - sublime-text
      - vagrant
      - virtualbox
      - eclipse-jee
      # - intellij-idea
      - skype
      - dropbox
